# Generated by Django 5.1.1 on 2024-09-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.CharField(default="Supplier-1", max_length=255),
        ),
    ]
