# Generated by Django 5.1.1 on 2024-09-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_supplier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="supplier",
        ),
    ]
