# Generated by Django 5.1.1 on 2024-10-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_supplier"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
